#!/bin/bash
cd "$(dirname "$0")"

/usr/bin/python run_server.py


# ;*******************************************************************
# ; monitoring	
# ;*******************************************************************
# [program:monitoring]
# command=/root/fastlanebot/run_server
# autostart=false
# autorestart=true
# startsecs=10
# startretries=3
# killasgroup=true
# stopasgroup=true
# redirect_stderr=false
# stdout_logfile=/var/log/carbon_monitoring_output.log
# stderr_logfile=/var/log/carbon_monitoring_error.log