#!/bin/bash
cd "$(dirname "$0")"

pwd
rm -rf fastlane_bot/tests/nbtest/*
mkdir fastlane_bot/tests/nbtest/
mkdir fastlane_bot/tests/nbtest_data/
cp resources/nbtest_data/* fastlane_bot/tests/nbtest_data/
touch fastlane_bot/tests/nbtest/__init__.py
python resources/NBTest/ConvertNBTest.py >/dev/null
#python resources/NBTest/ConvertNBTest.py
#mv fastlane_bot/tests/nbtest/* fastlane_bot/tests/
#pytest fastlane_bot/tests $1
pytest fastlane_bot/tests/nbtest $1