#!/bin/bash
cd "$(dirname "$0")"

# nodejs path/to/update/datafile.json
pushd resources/NBTest
python3 Analysis_015_ArbMonitoringBot.py > Analysis_015.latest.log
cat Analysis_015.latest.out >> Analysis_015.out
cat Analysis_015.latest.log >> Analysis_015.log
date >> Analysis_015.heartbeat
popd
