In [1]:
from tools.curves import ConstantProductCurve, CurveContainer, SimplePair
from tools.optimizer import CPCArbOptimizer, PairOptimizer, MargPOptimizer
CPC = ConstantProductCurve

import pandas as pd
import math as m

#print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(SimplePair))
#print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(CPC))
#print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(CurveContainer))
#print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(PairOptimizer))
print("{0.__name__} v{0.__VERSION__} ({0.__DATE__})".format(MargPOptimizer))

MargPOptimizer v6.0-beta01 (04/May/2024)


# Optimizer Testing (SEI2, May 2024)

This is a light workbook allowing to look at issues that may arise when running the optimizer on a specific set of curves. 

Instructions:

- locate the **exact** curve set to feed to the optimizer (it will be somewhere in the logging output, and it will be a list of ConstantProductCurve objects)
- assign it to the `CurvesRaw` variable as shown below
- add the missing token addresses to the `TOKENS` dict below
- provide consistent values for `PSTART`
- run the workbook

### >> Enter curves

Place curves here in the form

    CurvesRaw = [
        ConstantProductCurve(k=27518385.40998667, x=1272.2926367501436, x_act=0, ...),
        ConstantProductCurve(k=6.160500599566333e+18, x=11099999985.149971, x_act=0, ...),
    ...
    ]

In [2]:
# CurvesRaw = [
#     ConstantProductCurve(k=27518385.40998667, x=1272.2926367501436, x_act=0, y_act=2000.9999995236503, alpha=0.5, pair='0x514910771AF9Ca656af840dff83E8264EcF986CA/0x8E870D67F660D95d5be530380D0eC0bd388289E1', cid='0x425d5d4ad7243f88d9f4cde8da52863b45af1f64e05bede1299909bcaa6c52d1-0', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 2000.9999995236503, 'yint': 2000.9999995236503, 'A': 0.38144823884371704, 'B': 3.7416573867739373, 'pa': 16.99999999999995, 'pb': 13.99999999999997}),
#     ConstantProductCurve(k=6.160500599566333e+18, x=11099999985.149971, x_act=0, y_act=55.50000002646446, alpha=0.5, pair='0x8E870D67F660D95d5be530380D0eC0bd388289E1/0x514910771AF9Ca656af840dff83E8264EcF986CA', cid='0x425d5d4ad7243f88d9f4cde8da52863b45af1f64e05bede1299909bcaa6c52d1-1', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 55.50000002646446, 'yint': 55.50000002646446, 'A': 0, 'B': 0.22360678656963742, 'pa': 0.04999999999999889, 'pb': 0.04999999999999889}),
#     ConstantProductCurve(k=14449532.299465338, x=57487.82879658422, x_act=0, y_act=5.0, alpha=0.5, pair='0x514910771AF9Ca656af840dff83E8264EcF986CA/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', cid='0x3fcccfe0063b71fc973fab8dea39b6be9da80125910c10e57b924b3e4687295a-0', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 5.0, 'yint': 8.582730309868262, 'A': 0.002257868117407469, 'B': 0.06480740698407672, 'pa': 0.004497751124437756, 'pb': 0.004199999999999756}),
#     ConstantProductCurve(k=14456757.06563651, x=251.4750925240284, x_act=0, y_act=807.9145301701096, alpha=0.5, pair='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/0x514910771AF9Ca656af840dff83E8264EcF986CA', cid='0x3fcccfe0063b71fc973fab8dea39b6be9da80125910c10e57b924b3e4687295a-1', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 807.9145301701096, 'yint': 1974.7090228584536, 'A': 0.519359008452966, 'B': 14.907119849998594, 'pa': 237.97624997025295, 'pb': 222.22222222222211}),
#     ConstantProductCurve(k=56087178.30932376, x=131.6236694086859, x_act=0, y_act=15920.776548455418, alpha=0.5, pair='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/0x8E870D67F660D95d5be530380D0eC0bd388289E1', cid='0x6cc4b198ec4cf17fdced081b5611279be73e200711238068b5340e606ba86646-0', fee=2000, descr='carbon_v1 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 15920.776548455418, 'yint': 32755.67010983316, 'A': 4.373757425036729, 'B': 54.77225575051648, 'pa': 3498.2508745627138, 'pb': 2999.9999999999854}),
#     ConstantProductCurve(k=56059148.73497429, x=426117.72306081816, x_act=0, y_act=5.0, alpha=0.5, pair='0x8E870D67F660D95d5be530380D0eC0bd388289E1/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', cid='0x6cc4b198ec4cf17fdced081b5611279be73e200711238068b5340e606ba86646-1', fee=2000, descr='carbon_v1 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 5.0, 'yint': 10.106093048875099, 'A': 0.0013497708452092638, 'B': 0.016903085094568837, 'pa': 0.0003331667499582927, 'pb': 0.0002857142857142352})
# ]
# CCRaw = CurveContainer(CurvesRaw)

In [3]:
CurvesRaw = [
    ConstantProductCurve(k=27518385.40998667, x=1272.2926367501436, x_act=0, y_act=2000.9999995236503, alpha=0.5, pair='0x514910771AF9Ca656af840dff83E8264EcF986CA/0x8E870D67F660D95d5be530380D0eC0bd388289E1', cid='0x425d5d4ad7243f88d9f4cde8da52863b45af1f64e05bede1299909bcaa6c52d1-0', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 2000.9999995236503, 'yint': 2000.9999995236503, 'A': 0.38144823884371704, 'B': 3.7416573867739373, 'pa': 16.99999999999995, 'pb': 13.99999999999997}),
    #ConstantProductCurve(k=6.160500599566333e+18, x=11099999985.149971, x_act=0, y_act=55.50000002646446, alpha=0.5, pair='0x8E870D67F660D95d5be530380D0eC0bd388289E1/0x514910771AF9Ca656af840dff83E8264EcF986CA', cid='0x425d5d4ad7243f88d9f4cde8da52863b45af1f64e05bede1299909bcaa6c52d1-1', fee=2000, descr='carbon_v1 0x514910771AF9Ca656af840dff83E8264EcF986CA\\/0x8E870D67F660D95d5be530380D0eC0bd388289E1 2000', constr='carb', params={'exchange': 'carbon_v1', 'y': 55.50000002646446, 'yint': 55.50000002646446, 'A': 0, 'B': 0.22360678656963742, 'pa': 0.04999999999999889, 'pb': 0.04999999999999889}),
    CPC.from_pk(p= 230,  k=1*230*(100**2),  cid="ETH/LINK", pair='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/0x514910771AF9Ca656af840dff83E8264EcF986CA', ), 
    CPC.from_pk(p=3220,  k=1*3220*(100**2), cid="ETH/USDP", pair='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/0x8E870D67F660D95d5be530380D0eC0bd388289E1', ), 
]
CCRaw = CurveContainer(CurvesRaw)

In [4]:
help(ConstantProductCurve.from_pk)

Help on method from_pk in module tools.curves.cpc:

from_pk(p, k, *, x_act=None, y_act=None, pair=None, cid=None, fee=None, descr=None, params=None) method of abc.ABCMeta instance
    constructor: from k,p (and x_act, y_act)



### >> Enter prices

Provide current prices (`pstart`) here, in the format

    PRICES = {
        '0x8E87...': 0.0003087360213944532, 
        '0x5149...': 0.004372219704179475, 
        '0xEeee...': 1
    }
    
The price numeraire does not matter as long as they are all in the same numeraire. All tokens must be present. Additional tokens can be added and will be ignored. 

In [5]:
PRICES_RAW = {
    '0x8E870D67F660D95d5be530380D0eC0bd388289E1': 0.0003087360213944532, 
    '0x514910771AF9Ca656af840dff83E8264EcF986CA': 0.004372219704179475, 
    '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE': 1
}

### >> Enter tokens

Provide token tickers here, in the format

    TOKENS = {
        "0x5149...": "LINK",
        "0x8E87...": "USDP",
        "0xEeee...": "ETH",
    }
    
All tokens must be present. Additional tokens will be ignored. You must also provide the `TARGET_TOKEN` (default: first token of `TOKENS`)


In [6]:
TOKENS = {
    "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE": "ETH",
    "0x514910771AF9Ca656af840dff83E8264EcF986CA": "LINK",
    "0x8E870D67F660D95d5be530380D0eC0bd388289E1": "USDP",
}

TARGET_TOKEN_RAW = list(TOKENS)[0]
TARGET_TOKEN_RAW

'0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'

### >>> Run optimizer

please make sure that this line runs without errors (other than the error that needs to be addressed of course)

In [7]:
O = MargPOptimizer(CCRaw)
r = O.optimize(sfc=TARGET_TOKEN_RAW, params=dict(pstart=PRICES_RAW))
r

[margp_optimizer] WARNING - providing `pstart` as parameter is deprecated; use `pstart` variable instead


CPCArbOptimizer.MargpOptimizerResult(result=-0.05121777885030099, time=0.00048828125, method='margp', targettkn='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE', p_optimal_t=(0.00030712990834734163, 0.004391622735940103), dtokens_t=(3.128661774098873e-10, 1.659827830735594e-11), tokens_t=('0x8E870D67F660D95d5be530380D0eC0bd388289E1', '0x514910771AF9Ca656af840dff83E8264EcF986CA'), errormsg=None)

**do not worry about the code below here; this is for the actual testing and will be adapted as need be**

### >>> Preprocessing

Please ensure that this code runs without error. Errors here mean that the data provided above is not consistent.

In [8]:
def replace_tokens(dct):
    """replaces the token address with the token name in dct"""
    tkns = dct["pair"].split("/")
    for i in range(len(tkns)):
        #tkns[i] = TOKENS.get(tkns[i]) or tkns[i]
        tkns[i] = TOKENS[tkns[i]]
    dct["pair"] = "/".join(tkns)
    return dct

def p(pair=None, *, tknb=None, tknq=None, prices=None):
    "price of tknb in terms of tknq"
    if not pair is None:
        tknb, tknq = pair.split("/")
    p = prices or PRICES
    return p[tknb]/p[tknq]

def round_(x, *args):
    "forgiving round()"
    try:
        return round(x, *args)
    except:
        return x

def wbp(c):
    "width of the range in bp [0 means infty]"
    try:
        return max(int((c.p_max_primary()/c.p_min_primary() - 1)*10000), 1)
    except:
        return 0
    
def cid0(c):
    "shortened cid (for standard format ones)"
    if len(c.cid) < 20: return c.cid
    return f"{c.cid[2:6]}{c.cid[-2:]}"

If this fails this probably means that one of the tokens has not been defined above

In [9]:
CC = CurveContainer.from_dicts([replace_tokens(d) for d in CCRaw.asdicts()])
PRICES = {TOKENS[addr]:price for addr, price in PRICES_RAW.items()}
TARGET_TOKEN = TOKENS[TARGET_TOKEN_RAW]
PRICES

{'USDP': 0.0003087360213944532, 'LINK': 0.004372219704179475, 'ETH': 1}

In [10]:
def p(pair=None, *, tknb=None, tknq=None, prices=None):
    "price of tknb in terms of tknq"
    if not pair is None:
        tknb, tknq = pair.split("/")
    p = prices or PRICES
    return p[tknb]/p[tknq]

The code below ensures that in ETH/LINK, LINK is the quote token and ETH the base token (for better price displays)

In [11]:
SimplePair.NUMERAIRE_TOKENS["LINK"] = SimplePair.NUMERAIRE_TOKENS["ETH"] - 1
#SimplePair.NUMERAIRE_TOKENS

## Curves

In [12]:
print("Num curves:   ", len(CC))
print("Pairs:        ", set(c.pairo.primary_n for c in CC))
print("Target token: ", TARGET_TOKEN)

Num curves:    3
Pairs:         {'LINK/USDP', 'ETH/USDP', 'ETH/LINK'}
Target token:  ETH


In [13]:
PRICE_DECIMALS = 2
curvedata = [dict(
    cid0 = cid0(c),
    exch = c.params.get('exchange', "na"),
    pair = c.pairo.primary_n,
    mktp = round(p(c.pairo.primary_n), PRICE_DECIMALS),
    bs = c.buysell(),
    tkn = c.pairo.primary_tknb,
    p = round_(c.primaryp(), PRICE_DECIMALS),
    p_min = round_(c.p_min_primary(), PRICE_DECIMALS),
    p_max = round_(c.p_max_primary(), PRICE_DECIMALS),
    tknp = p(tknb=c.pairo.primary_tknb, tknq=TARGET_TOKEN),
    wbp = wbp(c),
    liq = round(c.tvl(tkn=c.pairo.primary_tknb), 2),
    liqtt = round(c.x_act*p(tknb=c.tknx, tknq=TARGET_TOKEN) + c.y_act*p(tknb=c.tkny, tknq=TARGET_TOKEN), 2),
) for c in CC]
#curvedata

- `cid0`: shortened CID (same as in `debug_tkn2`)
- `exch`: the type of the curve / exchange in question
- `pair`: the normalized pair of the curve
- `mktp`: the current market price of that pair (according to `PRICES_RAW`)
- `bs`: whether curves buys ("b"),  sells ("s") the primary tokenm, or both
- `tkn`: the primary token (base token of primary pair)
- `p`, `p_min`, `p_max`: the current / minimum / maximum price of the curve
- `tknp`: the price of `tkn` (as above) in terms of `TARGET_TOKEN`, as per the market price
- `wbp`: width of the range (p_max/p_min) in basis points 
- `liq`: liquidity (in units of `tkn` as defined above; converted at curve price)
- `liqtt`: total curve liquidity (in `TARGET_TOKEN` units; converted at `mktp`)


In [14]:
curvedf = pd.DataFrame(curvedata)
curvedf

cid0       exch       pair     mktp  bs   tkn       p  p_min  p_max  \
0    425d-0  carbon_v1  LINK/USDP    14.16   b  LINK    17.0   14.0   17.0   
1  ETH/LINK         na   ETH/LINK   228.72  bs   ETH   230.0    0.0    NaN   
2  ETH/USDP         na   ETH/USDP  3239.01  bs   ETH  3220.0    0.0    NaN   

       tknp   wbp     liq   liqtt  
0  0.004372  2142  117.71    0.62  
1  1.000000     0  200.00  200.56  
2  1.000000     0  200.00  199.41

- The arbitrageable curve is #0 that buys LINK against USDP on the way down from `17 to 14`, at an average price of `15.4 LINK/USDP`; liquidity is `0.6 ETH ~ 2000 USDP`
- The triangle is made up via two massive curves (20 ETH each) with price points at `230 ETH/LINK` and `3220 ETH/USDP` respectively, yielding an effective `ETH/LINK of 14`
- The average profit is `10%`, on a volume of `2000 USDP or 0.6 ETH`, ie `200 USD or 0.06 ETH`
- That is close enough to the actual `result 0.05 ETH` (see below), keeping in mind that there is still some slippage on the big curves

In [15]:
0.6*3220, m.sqrt(17*14), 3220/230, 15.4/14-1

(1932.0, 15.427248620541512, 14.0, 0.10000000000000009)

For reference, the CID dataframe `ciddf` (separate because the field is too long; can be joined to `curvedf` via index)

In [16]:
ciddf = pd.DataFrame([dict(cid=c.cid) for c in CC])
ciddf

cid
0  0x425d5d4ad7243f88d9f4cde8da52863b45af1f64e05b...
1                                           ETH/LINK
2                                           ETH/USDP

In [17]:
#help(CC[0])

In [18]:
#help(CC[0].pairo)

## MargPOptimizer

In [19]:
O = MargPOptimizer(CC)
r = O.optimize(sfc=TARGET_TOKEN, params=dict(
    pstart=PRICES,
    verbose=True,
    debug=False,
    debug_j=True,
    debug_dtkn=False,
    debug_dtkn2=False,
    debug_dtknd=True,
))
r

[margp_optimizer] targettkn = ETH
[margp_optimizer] WARNING - providing `pstart` as parameter is deprecated; use `pstart` variable instead
[margp_optimizer] crit=rel (eps=1e-06, unit=1, norm=L2)

[margp_optimizer] ETH <- USDP, LINK
[margp_optimizer] p    0.00, 0.00
[margp_optimizer] 1/p  3,239.01, 228.72

[margp_optimizer]
============= JACOBIAN% =============>>>
tknq ETH
dUSDP/d%pUSDP, dUSDP/d%pLINK
dLINK/d%pUSDP, dLINK/d%pLINK
<<<============= JACOBIAN% =============


[margp_optimizer]
============= JACOBIAN% =============>>>
[[-1704.90616999    98.21599834]
 [    6.93538284  -121.04274482]]
<<<============= JACOBIAN% =============


[margp_optimizer]
========== cycle 0 =======>>>
ETH <- USDP, LINK
dtkn   -938.737, 57.429
log p0 [-3.51041269678875, -2.359298022862449]
d logp [-0.00226877  0.00192028]
log p  [-3.51268146 -2.35737774]
p_t      (0.000307127382149018, 0.004391594784368945) ETH
p        0.00, 0.00
1/p      3,255.98, 227.71
crit     2.97e-03 [1; L2], eps=1e-06, c/e=3e+03]

CPCArbOptimizer.MargpOptimizerResult(result=-0.05121777885030099, time=0.0017211437225341797, method='margp', targettkn='ETH', p_optimal_t=(0.00030712990834734163, 0.004391622735940103), dtokens_t=(3.128661774098873e-10, 1.659827830735594e-11), tokens_t=('USDP', 'LINK'), errormsg=None)

In [20]:
r.result, r.targettkn, -r.result*3400

(-0.05121777885030099, 'ETH', 174.14044809102336)